const mongoose = require('mongoose');

const todosSchema = new mongoose.Schema({ 
    calorias: Number,
    comidasCompletadas: Number,
    SemanaUno: Array,
    SemanaDos: Array,
    SemanaTres: Array,
    SemanaCuatro: Array,
    CardUno: Array,
    CardDos:Array,
    CardTres: Array,
    Card4: Array,
    Card5: Array,
    Card6: Array,
    Card7: Array,
    Card8: Array,
    Card9: Array,
    Card10: Array,
    Card11: Array,
    Card12: Array,
    Card13: Array,
    Card14: Array,
    Card15: Array,
    Card16: Array,
    Card17: Array,
    Card18: Array,
    Card19: Array,
    Card20: Array,
    Card21: Array,
    Card22: Array,
    Card23: Array,
    Card24: Array,
    Card25: Array,
    Card26: Array,
    Card27: Array,
    Card28: Array,
    Card29: Array,
    Card30: Array,
    Card31: Array,
    Card32: Array,
    Card33: Array,
    Card34: Array,
    Card35: Array,
    Card36: Array,
    Card37: Array,
    Card38: Array,
    Card39: Array,
    Card40: Array,
    Card41: Array,
    Card42: Array,
    Card43: Array,
    Card44: Array,
    Card45: Array,
    Card46: Array,
    Card47: Array,
    Card48: Array,
    Card49: Array,
    Card50: Array,
    Card51: Array,
    Card52: Array,
    Card53: Array,
    Card54: Array,
    Card55: Array,
    Card56: Array,
    Card57: Array,
    Card58: Array,
    Card59: Array,
    Card60: Array,
    Card61: Array,
    Card62: Array,
    Card63: Array,
    Card64: Array,
    Card65: Array,
    Card66: Array,
    Card67: Array,
    Card68: Array,
    Card69: Array,
    Card70: Array,
    Card71: Array,
    Card72: Array,
    Card73: Array,
    Card74: Array,
    Card75: Array,
    Card76: Array,
    Card77: Array,
    Card78: Array,
    Card79: Array,
    Card80: Array,
    Card81: Array,
    Card82: Array,
    Card83: Array,
    Card84: Array,
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    }
});

todosSchema.set('toJSON', {
    transform: (document, returnedObject) => {
        returnedObject.id = returnedObject._id.toString();
        delete returnedObject._id;
        delete returnedObject.__v;
    }
});

const Recetas = mongoose.model('Recetas', todosSchema);

module.exports = Recetas;